"""Shared plumbing for agent-tool integrations.

An *integration* writes the files a specific AI coding tool reads from a project
directory: instruction/steering files, MCP server registration, prompt or command
files, hooks and spec artifacts.

Design: an integration is a **template directory** (``integrations/<name>/``,
force-included into the wheel) plus optional code-generated files. Adding a new
tool therefore means adding a directory and one registry entry — no new CLI code
and no changes to the runtime.
"""

from __future__ import annotations

from collections.abc import Iterable, Sequence
from dataclasses import dataclass, field
from pathlib import Path

from agent_kit.paths import AssetError, integrations_dir
from agent_kit.scaffold import render


class IntegrationError(RuntimeError):
    """Raised when an integration cannot be installed or inspected."""


@dataclass(frozen=True)
class IntegrationStatus:
    """Which of an integration's managed files are present."""

    name: str
    present: list[Path] = field(default_factory=list)
    missing: list[Path] = field(default_factory=list)

    @property
    def installed(self) -> bool:
        return not self.missing

    @property
    def total(self) -> int:
        return len(self.present) + len(self.missing)


class TemplateIntegration:
    """Base class for integrations driven by a template directory.

    Subclasses set :attr:`name` (the value used by ``--integration``) and may
    override :attr:`template_dir_name`, :attr:`placeholders` or
    :meth:`extra_files`.
    """

    #: Registry key and template directory name.
    name: str = "integration"
    #: Human-readable name for CLI output.
    title: str = "Integration"
    #: One-line description for ``agent-kit integration list``.
    description: str = ""
    #: Directory under ``integrations/`` (defaults to :attr:`name`).
    template_dir_name: str | None = None
    #: Files generated by code rather than copied from a template, relative to
    #: the project root. They participate in status/uninstall like any other.
    code_generated_files: tuple[str, ...] = ()

    # -- template resolution ----------------------------------------------
    @property
    def template_dir_name_resolved(self) -> str:
        return self.template_dir_name or self.name

    def template_dir(self) -> Path:
        """Directory holding this integration's templates."""
        try:
            return integrations_dir() / self.template_dir_name_resolved
        except AssetError as exc:  # pragma: no cover - packaging failure
            raise IntegrationError(str(exc)) from exc

    def destination_root(self, project_root: Path) -> Path:
        """Directory the templates are copied into (default: the project root).

        Integrations whose files live inside a single folder (Kiro's ``.kiro/``)
        override this so template layout stays readable.
        """
        return project_root

    def placeholders(self, project_root: Path, command: str) -> dict[str, str]:
        """Values substituted into ``{{PLACEHOLDER}}`` tokens."""
        return {
            "AGENT_KIT_COMMAND": command,
            "PROJECT_NAME": project_root.name,
            "PROJECT_ROOT": str(project_root),
            "DEFAULT_INPUT": "samples/requirement-analysis/input/sample-001.md",
            "DEFAULT_OUTPUT": "output/sample-001.md",
        }

    # -- file inventory ----------------------------------------------------
    def template_files(self, project_root: Path) -> list[Path]:
        """Project paths that this integration's templates produce."""
        template = self.template_dir()
        if not template.is_dir():  # pragma: no cover - packaging failure
            raise IntegrationError(f"Templates for '{self.name}' not found at {template}.")
        base = self.destination_root(Path(project_root))
        return [
            base / path.relative_to(template)
            for path in sorted(template.rglob("*"))
            if path.is_file()
        ]

    def managed_files(self, project_root: Path) -> list[Path]:
        """Every file this integration owns, templates and generated ones."""
        root = Path(project_root)
        base = self.destination_root(root)
        extra = [base / relative for relative in self.code_generated_files]
        return [*self.template_files(root), *extra]

    # -- lifecycle ---------------------------------------------------------
    def install(
        self,
        project_root: Path | str,
        force: bool = False,
        command: str = "agent-kit",
    ) -> list[Path]:
        """Write the integration into ``project_root``.

        Existing files are kept unless ``force`` is set, so user edits survive a
        re-install.

        Returns:
            The list of files written (sorted).
        """
        root = Path(project_root).resolve()
        template = self.template_dir()
        if not template.is_dir():  # pragma: no cover - packaging failure
            raise IntegrationError(f"Templates for '{self.name}' not found at {template}.")

        mapping = self.placeholders(root, command)
        base = self.destination_root(root)
        written: list[Path] = []

        for path in sorted(template.rglob("*")):
            destination = base / path.relative_to(template)
            if path.is_dir():
                destination.mkdir(parents=True, exist_ok=True)
                continue
            if destination.exists() and not force:
                continue
            destination.parent.mkdir(parents=True, exist_ok=True)
            destination.write_text(
                render(path.read_text(encoding="utf-8"), mapping),
                encoding="utf-8",
            )
            written.append(destination)

        written.extend(self.extra_files(root, force=force, command=command))
        return sorted(written)

    def extra_files(self, project_root: Path, force: bool, command: str) -> list[Path]:
        """Hook for files that need generated content (default: none)."""
        return []

    def status(self, project_root: Path | str) -> IntegrationStatus:
        root = Path(project_root)
        present: list[Path] = []
        missing: list[Path] = []
        for path in self.managed_files(root):
            (present if path.is_file() else missing).append(path)
        return IntegrationStatus(name=self.name, present=present, missing=missing)

    def uninstall(self, project_root: Path | str) -> list[Path]:
        """Remove managed files and prune directories that become empty."""
        root = Path(project_root).resolve()
        removed: list[Path] = []
        for path in self.managed_files(root):
            if path.is_file():
                path.unlink()
                removed.append(path)

        for directory in sorted(
            {path.parent for path in removed},
            key=lambda item: len(item.parts),
            reverse=True,
        ):
            current = directory
            while current != root and root in current.parents:
                try:
                    current.rmdir()
                except OSError:
                    break  # not empty: user content stays
                current = current.parent
        return removed


def parse_integration_names(values: str | Sequence[str] | None) -> list[str]:
    """Normalise CLI input into an ordered, de-duplicated list of names.

    Accepts ``"kiro"``, ``"kiro,claude"``, ``["kiro", "claude"]`` or any mix.
    """
    if values is None:
        return []
    if isinstance(values, str):
        values = [values]

    names: list[str] = []
    for value in values:
        for part in str(value).split(","):
            name = part.strip().lower()
            if name and name not in names:
                names.append(name)
    return names


def install_many(
    integrations: Iterable[TemplateIntegration],
    project_root: Path | str,
    force: bool = False,
    command: str = "agent-kit",
) -> dict[str, list[Path]]:
    """Install several integrations, returning ``{name: written_paths}``."""
    return {
        integration.name: integration.install(project_root, force=force, command=command)
        for integration in integrations
    }


__all__ = [
    "IntegrationError",
    "IntegrationStatus",
    "TemplateIntegration",
    "install_many",
    "parse_integration_names",
]
